baseURL = "https://kanakokoike.github.io/top/"
languageCode = "ja-jp"
title = "福嶋佳菜子 | 認定遺伝カウンセラー／国際医療福祉大学 助教"

# During Hugo builds, ignore static/index.html so that the
# theme-rendered homepage takes precedence. Static index is
# still used by CI fallback when Hugo fails.
ignoreFiles = ["^static/index\\.html$"]

[module]
  # Wowchemy/Hugo Blox modules for Academic-style site
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/starters/academic-cv"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "What's New"
    url  = "#news"
    weight = 10
  [[menu.main]]
    name = "Research"
    url  = "#research"
    weight = 20
  [[menu.main]]
    name = "Publications"
    url  = "#publications"
    weight = 30
  [[menu.main]]
    name = "Projects"
    url  = "#projects"
    weight = 40
  [[menu.main]]
    name = "Teaching"
    url  = "#teaching"
    weight = 50
  [[menu.main]]
    name = "Awards"
    url  = "#awards"
    weight = 60
  [[menu.main]]
    name = "Media"
    url  = "#media"
    weight = 70
  [[menu.main]]
    name = "Profiles"
    url  = "#profiles"
    weight = 80
  [[menu.main]]
    name = "Contact"
    url  = "#contact"
    weight = 90
