baseURL = "https://kanakokoike.github.io/top/"
languageCode = "ja-jp"
title = "Koike Kanako"

# During Hugo builds, ignore static/index.html so that the
# theme-rendered homepage takes precedence. Static index is
# still used by CI fallback when Hugo fails.
ignoreFiles = ["^static/index\\.html$"]

[build]
  writeStats = true

[module]
  # Wowchemy/Hugo Blox modules for Academic-style site
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/starters/academic-cv"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "What's New"
    url  = "#news"
    weight = 10
  [[menu.main]]
    name = "Publications"
    url  = "#publications"
    weight = 20
  [[menu.main]]
    name = "Research"
    url  = "#research"
    weight = 30
  [[menu.main]]
    name = "Projects"
    url  = "#projects"
    weight = 40
  [[menu.main]]
    name = "Teaching"
    url  = "#teaching"
    weight = 50
  [[menu.main]]
    name = "Awards"
    url  = "#awards"
    weight = 60
  [[menu.main]]
    name = "Media"
    url  = "#media"
    weight = 70
  [[menu.main]]
    name = "Profiles"
    url  = "#profiles"
    weight = 80
  [[menu.main]]
    name = "Contact"
    url  = "#contact"
    weight = 90

[params]
  [params.header]
    [params.header.navbar]
      [params.header.navbar.logo]
        # Brand text shown at top-left of navbar
        text = "Kanako Koike FUKUSHIMA"

  [params.marketing]
    [params.marketing.seo]
      site_type = "Person"
      description = "若年層の突然死の予防と家族支援をめざす Molecular Autopsy の研究者・認定遺伝カウンセラー。国際医療福祉大学 助教。論文・科研費・教育・メディア情報を掲載。"
      twitter = "kanakokoike_78"
      og_locale = "ja_JP"
